control:
  bot:
    api_key: 
  tools:
    - searchOnlineTool
dao:
  db:
    activate: false
    db_name: storage/db/db.sqlite
    db_type: sqlite
    db_url: null
    password: null
    user: null
  file:
    activate: false
    file_path: storage/file
runtime:
  agent_path: storage/agent
  current_session_id: 3347bf6e-c28f-4d0c-93f4-9093dfc6d413
  history_path: storage/history
view:
  flask:
    activate: false
    debug: true
    host: localhost
    port: 5000
  taipy:
    activate: true
